version: "3.9"
services:
 system-service:
  image: mehmetdem110/api_herexamen_project
  ports:
    - "8111:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
