version: "3.9"
services:
 system-service:
  build:
   context: "."
   dockerfile: Dockerfile
  ports:
    - "8111:8000"
  volumes:
    - ./app/test.db:/code/test.db
  
volumes:
  sqlite_useritems_volume:
